require 'functor'

require 'functor/accrue'
require 'functor/accumulate'
require 'functor/as'
require 'functor/as_s'
require 'functor/data'
require 'functor/eigen'
require 'functor/every'
require 'functor/ewise'
require 'functor/file'
require 'functor/fx'
require 'functor/not'
require 'functor/per'
require 'functor/reflect'
require 'functor/respond'

